from PIL import Image, ImageOps

INPUT_FILE = "image.png"  
OUTPUT_FILE = "bg1.inc"   

pal = [
    (0,0,0), (0,0,170), (0,170,0), (0,170,170),
    (170,0,0), (170,0,170), (170,85,0), (170,170,170),
    (85,85,85), (85,85,255), (85,255,85), (85,255,255),
    (255,85,85), (255,85,255), (255,255,85), (255,255,255)
]

def get_nearest_color(rgb):
    r, g, b = rgb[:3]
    diff = max(r, g, b) - min(r, g, b)
    if diff < 25: 
        allowed_greys = [0, 7, 8, 15]
        return min(allowed_greys, key=lambda i: (r-pal[i][0])**2 + (g-pal[i][1])**2 + (b-pal[i][2])**2)
    best_i = 0
    min_dist = float('inf')
    for i, (pr, pg, pb) in enumerate(pal):
        dist = (r-pr)**2 * 0.3 + (g-pg)**2 * 0.59 + (b-pb)**2 * 0.11
        if dist < min_dist:
            min_dist = dist
            best_i = i
    return best_i

img = Image.open(INPUT_FILE).convert("RGB")
from PIL import ImageEnhance
img = ImageEnhance.Contrast(img).enhance(1.3)
img = Image.Resampling and img.resize((80, 50), Image.Resampling.LANCZOS) or img.resize((80, 50), Image.LANCZOS)
pixels = img.load()
out_data = bytearray()

for y in range(25):
    for x in range(80):
        top = get_nearest_color(pixels[x, y*2])
        bot = get_nearest_color(pixels[x, y*2+1])
        out_data.append(0xDF) 
        out_data.append((bot << 4) | top) 

# Записуємо як .inc файл для Асемблера
with open(OUTPUT_FILE, "w") as f:
    f.write("; Background data generated by python\n")
    for i in range(0, len(out_data), 16):
        chunk = out_data[i:i+16]
        f.write("DB " + ", ".join([f"0{b:02X}h" for b in chunk]) + "\n")

print("Done generating INC file!")