font_data LABEL BYTE

;Pawn
DB 00h, 00h, 00h, 18h, 3Ch, 3Ch, 18h, 18h
DB 3Ch, 7Eh, 7Eh, 3Ch, 7Eh, 0FFh, 0FFh, 00h

;Knight
DB 00h, 00h, 0Ch, 1Eh, 3Fh, 7Eh, 7Ch, 3Ch
DB 1Eh, 3Eh, 7Eh, 7Eh, 0FFh, 0FFh, 00h, 00h

;Bishop
DB 00h, 00h, 18h, 3Ch, 7Eh, 5Ah, 7Eh, 3Ch
DB 18h, 3Ch, 7Eh, 7Eh, 0FFh, 0FFh, 00h, 00h

;Rook
DB 00h, 00h, 00h, 0DBh, 0DBh, 0FFh, 7Eh, 3Ch
DB 3Ch, 3Ch, 3Ch, 7Eh, 0FFh, 0FFh, 00h, 00h

;Queen
DB 00h, 00h, 54h, 54h, 7Eh, 3Ch, 18h, 18h
DB 3Ch, 7Eh, 3Ch, 7Eh, 0FFh, 0FFh, 00h, 00h

;King 
DB 00h, 18h, 3Ch, 18h, 7Eh, 0FFh, 0DBh, 0FFh
DB 7Eh, 3Ch, 7Eh, 7Eh, 0FFh, 0FFh, 00h, 00h